language: node_js
node_js:
  - 6
before_script:
  - npm install -g gulp
script:
  - echo No tests
  - echo test > test
# Put the scraping here

after_success:
  - echo $GIT_PRIVATE_KEY | base64 --decode > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - echo hi > hi
  - git commit -a -m "test commit!"
  - ls -lah .travis
  - git remote add deploy git@github.com:ryanhugh/NEU-employee-directory.git
  - git push deploy

cache: yarn

notifications:
  email:
    on_success: never