language: node_js
node_js:
  - 6
before_script:
  - npm install -g gulp
script:
  - echo No tests
  - echo test > test
# Put the scraping here

after_success:
  - eval "$(ssh-agent -s)"
  - echo $GIT_PRIVATE_KEY | base64 --decode > ~/deploy_key
  - chmod 600 ~/deploy_key
  - ssh-add ~/deploy_key
  - git pull
  - git checkout gh-pages
  - git merge master
  - echo hi > hi
  - git config --global user.email "ryanhughes624+gitbot@gmail.com"
  - git config --global user.name "data-updater-bot"
  - git add hi
  - git commit -a -m "test commit!"
  - ls -lah ~
  - cat ~/deploy_key | wc -l
  - git remote add deploy git@github.com:ryanhugh/NEU-employee-directory.git
  - git config --global push.default simple
  - git push deploy

cache: yarn
#

notifications:
  email:
    on_success: never